jenkins:
  host: 'http://10.161.10.198:8080'
  username: 'admin'
  password: 'admin@123'

db:
  url: 'postgresql://si_hcmp_teraprod:si_hcmp_teraprod@5432@/HCMP_TERAFORM_PROD?host=10.166.16.160&port=5432'
  schema: 'hcmp'
  
terraform_db:
  url: 'postgresql://si_hcmp_teraprod:si_hcmp_teraprod@5432@/HCMP_TERAFORM_PROD?host=10.166.16.160&port=5432'
  schema: 'terraform_remote_state'

server:
  ip: '0.0.0.0'
  port: 8082
  name: 'Orchestrator'
  backend_cors_orgins: ['*']
  
rmq:
  server: '10.166.16.98'
  port: 31387
  virtual_host: '/'
  user: 'oLdG8Byye1T70cxX2_c99iFIynPzSmQM'
  password: '6udmXsKGDpeYuUNShTC7UXERYQdmNfhM'
  queue: 'orchestrator-prod'
  exchange: 'orchestrator'
  
  
password-encryption:
  key: 'hN5w8cHOcE5iazBkZtLSCcUkt-30ftOX6iDdjyr3H9c='    

ldap:
  ldap_server: 'ldap://adldap.in.xxx.com:389'
  base_dn: 'DC=in,DC=xxx,DC=com'
  search_filter: '(&(objectclass=user)(sAMAccountName={}))'

response_list:
  exclude: 'random_id,random_uuid'

teams:
  portal_url: "http://13.126.60.149:4200/orchestration/transactions/{}"
  team_webhook_url: "https://htcinc0.webhook.office.com/webhookb2/ccd386c8-ca2f-4bc7-99ec-b87859bd4c05@249afc7c-06ae-4bc9-b93e-1232b68ce6fe/IncomingWebhook/7a76dd4dd2df4a7bbd08e44bd7c87f14/2ccefe53-9c19-44ee-8b2c-ee5a887bf440"
